main: me.cjcrafter.schematicbrushes.SchematicBrushes
author: CJCrafter
version: 1.1.1
api-version: "1.14"
name: SchematicBrushes
depend:
  - WorldEdit
commands:
  schematicbrushes:
    permission: schematicbrushes.admin
    description: main command for SchematicBrushes
    aliases:
      - schematicbrushes
      - sb
permissions:
  schematicbrushes.admin:
    description: Commands for schematic brushes
  schematicbrushes.use:
    description: Use the brushes