main: me.cjcrafter.schematicbrushes.SchematicBrushes
author: CJCrafter
version: 2.0.0
api-version: "1.15"
name: SchematicBrushes
depend:
  - WorldEdit
permissions:
  schematicbrushes.admin:
    description: Commands for schematic brushes
  schematicbrushes.use:
    description: Use the brushes